jobs:
  - deployment: Deploy
    environment: $(aksEnvironment)
    displayName: Deploy to Azure Kubernetes Service
    pool:
      vmImage: $(vmImage)
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo "##vso[task.setvariable variable=imageTag]$(npm run --silent my-version)"
              displayName: Image Tag - use app version

            - template: ../steps/append-sha.yaml

            - template: ../steps/debug-vars.yaml

            - task: DownloadPipelineArtifact@2
              inputs:
                buildType: 'current'
                artifactName: 'manifests'
                targetPath: '$(Pipeline.Workspace)/manifests'

            - task: KubernetesManifest@0
              displayName: Create Kubernetes secret
              inputs:
                action: 'createSecret'
                kubernetesServiceConnection: 'test-aks-master-enable'
                namespace: 'ihb'
                secretType: 'dockerRegistry'
                secretName: $(azAcrSecret)
                dockerRegistryEndpoint: 'tylabcr'

            - task: KubernetesManifest@0
              displayName: Deploy image to cluster
              inputs:
                action: 'deploy'
                kubernetesServiceConnection: 'test-aks-master-enable'
                namespace: 'ihb'
                manifests: |
                  $(Pipeline.Workspace)/manifests/deployment/deployment.yaml
                  $(Pipeline.Workspace)/manifests/service/service.yaml
                imagePullSecrets: $(azAcrSecret)
                containers: '$(containerRegistry)/$(imageRepository):$(tag)'